title: scipiper tips and tricks
description: Common issues and approaches for debugging scipiper pipelines
template:
  name: ds-pipelines-2-template
  repo: ds-pipelines-2
before:
  - type: createIssue
    title: Recognize the unique demands of big collaborative pipelines
    body: 00-overview.md
    store:
      overview_issue_url: '{{ result.data.html_url }}'
steps:
  - title: Get the big picture
    description: Recognize the unique demands of big collaborative pipelines
    link: '{{ store.overview_issue_url }}'
    event: issues.assigned
    actions:
      - type: respond
        with: 01-access-caches.md
        store:
          install_activity_url: '{{ result.data.html_url }}'
